### ISSUE TITLE
Sub-To-Browser and Pub-From-Browser Are Outdated

### ISSUE THREAD

**Issue by daniel-d-truong** [pion/ion-examples#46]
### What did you do?
I tried running both [pub-from-browser](https://github.com/pion/ion-examples/tree/master/ion-sfu/pub-from-browser) and [sub-to-browser](https://github.com/pion/ion-examples/tree/master/ion-sfu/pub-from-browser) but both examples don't seem to work out of the box. Specifically, when I try to get the package or run it locally I'll get the following error: 

```
go: finding module for package github.com/pion/ion-sfu/cmd/server/grpc/proto
../../go/pkg/mod/github.com/pion/ion-examples@v0.0.0-20201119070420-9b701768e6d9/ion-sfu/pub-from-browser/main.go:12:2: no matching versions for query "latest"
```

I'm certain this is because the package directory is supposed to be `github.com/pion/ion-sfu/cmd/signal/grpc/proto` instead but even with that change, I got a couple of compile errors and was unsure how to resolve, such as the payload portion of JoinRequest (since Offer seems to have been replaced by Description?). I'm very new to all this stuff, so any help getting this to work out of the box would be extremely helpful. Thanks!

**Comment by shyaminayesh** [comment]
same for pub-from-disk

**Comment by leewardbound** [comment]
Hi there, sorry for the frustration you had with this repo; amidst rapid development to the `ion-sfu` codebase, these examples became unmaintained (by me!). We now suggest you use `ion-sdk-go`, which I find makes it nearly trivial to implement all of these examples, and more!

We've made the decision to archive this repo because nobody has time to maintain it, and we want to encourage `ion-sdk-go` use instead.

Closing this issue and archiving the repository! #64
