### ISSUE TITLE
Some of the examples require ion-sfu <= v1.0.22

### ISSUE THREAD

**Issue by tomsun** [pion/ion-examples#47]
Instructions in README:
[go build cmd/server/json-rpc/main.go
](https://github.com/pion/ion-examples/blame/master/ion-sfu/pub-sub-in-browser/README.md#L10
)

in https://github.com/pion/ion-sfu/commit/82edb040043f0421ff0bc1d3ce9b4bd5a08d0429#diff-3f4baa66ede0b4bc4a7fb43afb7a9538cae51bd4a73ea564ba5f2b01f6aa03b5 however, those files move to `cmd/signal/...`

if I check out ion-sfu from tag `v1.0.22` and use https://jsfiddle.net/8gcrvojw/ everything works as expected: two browser windows can publish and see each other's video

If I check out `v1.0.23` and use `cmd/signal/json-rpc/main.go` instead, then both browser windows claim to be connected, but neither gets the other's video

If I use more recent versions of ion-sfu, I get an explicit error client-side:

```
Logs
Publishing stream
Got publish answer
TypeError: Cannot add a candidate without specifying either sdpMid or sdpMLineIndex
...
```

**Comment by tomsun** [comment]
https://github.com/pion/ion-examples/pull/30 breaks various examples by un-pinning ion-sfu from 1.0.22 which brings along the cmd/server -> cmd/signal change

For example `pub-from-disk-using-grpc` after #30:

> main.go:13:2: module github.com/pion/ion-sfu@latest found (v1.8.1), but does not contain package github.com/pion/ion-sfu/cmd/server/grpc/proto

**Comment by tomsun** [comment]
This looks like part of it: https://github.com/pion/ion-sfu/pull/305

What's a good place to read up on the motivation for 2PC, beyond PR's "issues raised of using a single PC on large sessions", @OrlandoCo ( @Sean-Der ) ?  (Does the producer get swamped by all the consumer tracks in 1PC config, but gets higher priority if it has its own PC, or something like that? Is it likely that ion-sfu stays on this convention going forward or is it more of an experiment?)

Breaking changes but only a minor version bump, so one should probably not assume ion-sfu:s version no follows semver?

**Comment by leewardbound** [comment]
Hi there, sorry for the frustration you had with this repo; amidst rapid development to the `ion-sfu` codebase, these examples became unmaintained (by me!). We now suggest you use `ion-sdk-go`, which I find makes it nearly trivial to implement all of these examples, and more!

I think I can repeat what I have heard, regarding the 2PC decision - Orlando got a lot of questions of this nature, and ultimately, he spent a ton of time trying to optimize and reduce to 1PC architecture; however, the old structure was always prone to (i think) something like a server side locking issue, due to asynchronous publish-and-subscribe offer/answer combinations being sent at the same time. The 2 PC change made even more sense in the context of establishing a dedicated `ion-sfu` DataChannel on the first PC (which is used to negotiate the second PC, and I believe is now exposing client API commands like simulcast layer switching and track volume statistics).

We've made the decision to archive this repo because nobody has time to maintain it, and we want to encourage `ion-sdk-go` use instead.

Closing this issue and archiving the repository! #64
