### ISSUE TITLE
Proposal: Deprecate this repository

### ISSUE THREAD

**Issue by leewardbound** [pion/ion-examples#64]
+ This young repository has 3 authors and about 30 commits

+ The repository is fragmented between examples for `ion:0.4.6` (very outdated, pending new ion API before any updates) and newer examples for `ion-sfu` (at many versions from `1.0` to `1.5`, but no examples for recent versions)

+ Most-or-all of these examples are just "pub from disk/mediadevice" and "sub to disk" variants - these are now better represented by `ion-sdk-go` and the `ion-sdk-go/examples` folder, which achieves the same result with less code and less potential for bugs

+ I created this repository, but I don't have the skills or time to maintain it, I've gotten stuck trying to modernize these examples and I think it's better to use the `ion-sdk-go` client for all these cases now

@TannerGabriel @tarrencev - with both your approval (as the other 2 authors here), I'll go thru the Readme and Description and mark DEPRECATED everywhere, with links to `ion-sdk-go`

**Comment by Sean-Der** [comment]
I am in support of this.

I also am going to make some tooling to help us be better in the future. I am going to loop every Pion repo that isn't deprecated and generate some stats around issues/commits/PRs etc.. if anyone knows an existing tool that would be so helpful. Was hoping to generate some HTML/CSS/JS and setup a daily job and put on pion.ly/project-status ?

 @robin-raymond said he had a lot of frustration getting started because he couldn't figure out what was active/deprecated.

**Comment by TannerGabriel** [comment]
I'm also in support of deprecating the repository. I can also currently not find the time to properly maintain the repository examples and think that the `ion-sdk-go` is a great and easy alternative.

Also, I really like the idea of having some project status information @Sean-Der.

**Comment by leewardbound** [comment]
I've updated the README and Description with "DEPRECATED please use ion-sdk-go", and I'll mark this repository as Archived - Read Only!
